### ISSUE TITLE
problems getting started with ansibleautodoc

### ISSUE THREAD

**Issue by NicoWde** [shirou/sphinxcontrib-ansibleautodoc#1]
Hey there shirou,

I got following problem when adding the ansibleautotask to my "test" web.yml

```
ERROR: Syntax Error while loading YAML script, web.yml
Note: The error may actually appear before this position: line 28, column 13

  ansibleautotask:: second task
   :playbook: ../ansible/web.yml
```

maybe I got something in your very short introduction... wrong? 

I hope you can help me! :+1:

**Comment by shirou** [comment]
Hi, it seems ansible playbook YAML syntax error, not sphinx.
Could you check that playbook is valid and working?

**Comment by NicoWde** [comment]
?Hey there,

I used your example and added it into one of my working(!) Playbooks... may you provide me a test playbook of yours?

Thanks!

---

Von: shirou notifications@github.com
Gesendet: Donnerstag, 8. September 2016 11:03
An: shirou/sphinxcontrib-ansibleautodoc
Cc: NicoWde; Author
Betreff: Re: [shirou/sphinxcontrib-ansibleautodoc] problems getting started with ansibleautodoc (#1)

Hi, it seems ansible playbook YAML syntax error, not sphinx.
Could you check that playbook is valid and working?

##

**Comment by shirou** [comment]
You mean [index.rst](https://raw.githubusercontent.com/shirou/sphinxcontrib-ansibleautodoc/master/tests/sphinx/index.rst) and [web.yml](https://github.com/shirou/sphinxcontrib-ansibleautodoc/blob/master/tests/ansible/web.yml) in this repository? It works on my environment (sphinx 1.4.5).
